version: 0.2

phases:
    pre_build:
        - echo "[STATUS] Starting build"
        - mkdir build
    build:
        - docker build -t rhobot build
    post_build:
        - echo "[STATUS] Stopping build"
artifacts:
    - build/*
