version: 0.2

phases:
    pre_build:
        commands:
            - echo "[STATUS] Signing in to ECR"
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    build:
        commands:
            - echo "[STATUS] Building Docker image"
            - docker build -t $IMAGE_REPO_NAME:rhobot .
            - docker tag $IMAGE_REPO_NAME:rhobot $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:rhobot
    post_build:
        commands:
            - echo "[STATUS] Build complete"
            - echo "[STATUS] Pushing Docker image to ECR"
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:rhobot
artifacts:
    files:
        - pull-docker-image
        - application-start
