version: 0.2

phases:
    pre_build:
        commands:
            - echo "[STATUS] Starting build"
            - mkdir build
    build:
        commands:
            - docker build -t rhobot -o build .
    post_build:
        commands:
            - echo "[STATUS] Stopping build"
            - ls build
artifacts:
    files:
        - build/*
