version: 0.2

phases:
    pre_build:
        commands:
            - echo "[STATUS] Signing in to ECR"
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - echo "[STATUS] Installing npm dependencies"
            - npm install --only=dev
    build:
        commands:
            - export DOCKER_IMAGE_TAG="rhobot:$(git rev-parse HEAD)"
            - echo "[STATUS] Rendering template files"
            - npm run renderTemplates
            - echo "[STATUS] Building Docker image for ${DOCKER_IMAGE_TAG}"
            - docker build -t "${DOCKER_IMAGE_TAG}" .
            - docker tag "${DOCKER_IMAGE_TAG}" "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${DOCKER_IMAGE_TAG}"
    post_build:
        commands:
            - echo "[STATUS] Build complete"
            - echo "[STATUS] Pushing Docker image to ECR"
            - docker push "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${DOCKER_IMAGE_TAG}"
artifacts:
    files:
        - pull-docker-image
        - application-start
        - appspec.yml
        - creds.yaml
