version: 0.2

phases:
    pre_build:
        commands:
            - echo "[STATUS] Starting build"
            - mkdir build
    build:
        commands:
            - docker build --output type=tar,dest=build/rhobot.tar .
            - echo "[STATUS] Validating contents of the build dir"
            - pwd
            - ls
            - ls build
    post_build:
        commands:
            - echo "[STATUS] Stopping build"
            - ls build
artifacts:
    files:
        - build/*
